server:
  port: ${ORDER_COMMAND_SERVER_PORT_IN}

spring:
  application:
    name: order-command-server

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT_OUT}/${MARIADB_DATABASE}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
