server:
  port: ${ORDER_QUERY_SERVER_PORT_IN}

spring:
  application:
    name: order-query-server

  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT_OUT}/${MONGODB_DATABASE}