name: Build and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # 수동 실행도 허용

jobs:
  # -------------------------------
  # 1. 변경된 디렉토리 감지
  # -------------------------------
  detect-changes:
    name: Detect changed services
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.filter.outputs.command }}
      query: ${{ steps.filter.outputs.query }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect folder changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            command:
              - 'order-command-server/**'
            query:
              - 'order-query-server/**'
            web:
              - 'web-server/**'

  # -------------------------------
  # 2. order-command-server 빌드 & 푸시
  # -------------------------------
  build-command:
    name: Build order-command-server
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.command == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push order-command-server
        uses: docker/build-push-action@v6
        with:
          context: ./order-command-server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/order-command-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/order-command-server:${{ github.sha }}

  # -------------------------------
  # 3. order-query-server 빌드 & 푸시
  # -------------------------------
  build-query:
    name: Build order-query-server
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.query == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push order-query-server
        uses: docker/build-push-action@v6
        with:
          context: ./order-query-server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/order-query-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/order-query-server:${{ github.sha }}

  # -------------------------------
  # 4. web-server 빌드 & 푸시
  # -------------------------------
  build-web:
    name: Build web-server
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push web-server
        uses: docker/build-push-action@v6
        with:
          context: ./web-server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/web-server:${{ github.sha }}
