name: CI pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - "order-command-server/**"
      - "order-query-server/**"
      - "web-server/**"

jobs:
  build-order-command:
    if: contains(github.event.head_commit.message, 'order-command-server') || contains(toJson(github.event.commits.*.modified), 'order-command-server/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push order-command-server
        uses: docker/build-push-action@v6
        with:
          context: ./order-command-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-command-server:latest

  build-order-query:
    if: contains(toJson(github.event.commits.*.modified), 'order-query-server/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push order-query-server
        uses: docker/build-push-action@v6
        with:
          context: ./order-query-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-query-server:latest

  build-web:
    if: contains(toJson(github.event.commits.*.modified), 'web-server/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push web-server
        uses: docker/build-push-action@v6
        with:
          context: ./web-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-server:latest
